import { useState } from 'react';
import PageHeader from '../PageHeader';
import { mockGeneratedReports, mockReportStats } from '../mockData';
import type { ReportType } from '../types';

const reportTypes: ReportType[] = ['Inventory Summary', 'Beneficiary Logs', 'Processing Yield'];

export default function Reports() {
  const [reportType, setReportType] = useState<ReportType | ''>('');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');

  const handleGenerate = () => {
    // No backend yet — once the API exists, this should request a report
    // for the selected type/date range and add it to the table below.
    if (!reportType) {
      alert('Select a report type first.');
      return;
    }
    alert(
      `Generate "${reportType}"${startDate || endDate ? ` (${startDate || '…'} to ${endDate || '…'})` : ''} — hook this up once the backend is ready.`
    );
  };

  return (
    <>
      <PageHeader title="Reports & Analytics" />

      <div className="admin-stat-grid">
        <div className="admin-stat-card tone-green">
          <div className="admin-stat-label">Total Donors<br />(Current Month)</div>
          <div className="admin-stat-value">{mockReportStats.totalDonorsThisMonth}</div>
        </div>
        <div className="admin-stat-card tone-amber">
          <div className="admin-stat-label">Total Volume Collected<br />(Liters)</div>
          <div className="admin-stat-value">{mockReportStats.totalVolumeCollectedLiters}</div>
        </div>
        <div className="admin-stat-card tone-blue">
          <div className="admin-stat-label">Total Volume Dispensed<br />(Liters)</div>
          <div className="admin-stat-value">{mockReportStats.totalVolumeDispensedLiters}</div>
        </div>
        <div className="admin-stat-card tone-red">
          <div className="admin-stat-label">Expired</div>
          <div className="admin-stat-value">{mockReportStats.expired}</div>
        </div>
      </div>

      <div className="admin-report-controls">
        <div className="admin-report-field">
          <label htmlFor="report-type">Select Report Type</label>
          <select
            id="report-type"
            value={reportType}
            onChange={e => setReportType(e.target.value as ReportType)}
          >
            <option value="" disabled>Select Report Type</option>
            {reportTypes.map(rt => (
              <option key={rt} value={rt}>{rt}</option>
            ))}
          </select>
        </div>
        <div className="admin-report-field">
          <label htmlFor="report-start">Start Date</label>
          <input
            id="report-start"
            type="text"
            placeholder="Enter Date here"
            value={startDate}
            onChange={e => setStartDate(e.target.value)}
          />
        </div>
        <div className="admin-report-field">
          <label htmlFor="report-end">End Date</label>
          <input
            id="report-end"
            type="text"
            placeholder="Enter Date here"
            value={endDate}
            onChange={e => setEndDate(e.target.value)}
          />
        </div>
        <button type="button" className="admin-pill-action-btn admin-generate-btn" onClick={handleGenerate}>
          GENERATE
        </button>
      </div>

      <div className="admin-table-wrap">
        <div className="admin-table-scroll">
        <table className="admin-table">
          <thead>
            <tr>
              <th>Report Name</th>
              <th>Date Generated</th>
              <th>Generated By</th>
              <th>Format</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {mockGeneratedReports.length === 0 && (
              <tr className="admin-table-empty-row">
                <td colSpan={5}>No reports generated yet.</td>
              </tr>
            )}
            {mockGeneratedReports.map((r, i) => (
              <tr key={`${r.reportName}-${r.format}-${i}`}>
                <td className="admin-table-name">{r.reportName}</td>
                <td>{r.dateGenerated}</td>
                <td>{r.generatedBy}</td>
                <td>{r.format}</td>
                <td>
                  <a className="admin-file-link" href={r.downloadUrl ?? '#'}>
                    ⬇️ Download
                  </a>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        </div>
      </div>
    </>
  );
}
